### PR TITLE
Issue 2 default parameters

### LINKED ISSUE #2: Make all toView: parameters an optional UIView (for consistency)
### Description

I recently changed to non optionals for certain methods to be non-optional (see https://github.com/ustwo/autolayout-helper-swift/commit/5c09f94e6bb4ba53abacd4ef8b71e9db5dca33c2) but I'm rethinking and wondering if its better that Cocoa crashes inside UIKit if you send in a nil superview instead of it being a no-op (does nothing)
### Solutions
- We could / should change back to optionals also so its easier to integrate and consistent across all methods. Note if you use a method that needs a toView then it will crash when the constraint is created
- Or we could go one step further and make some use default params to reduce method chaining
- Other??

What do you think? @danieladias @chris59david @jamaine-ustwo 

Note. should merge PR #1 first

### PR DESCRIPTION
**Pull request by madhikarma**
Fixes #2 so that the same method can be called with less parameters 

e.g. <code>viewA.addLeftConstraint(toView: viewB)</code> 

or in full 

<code>addLeftConstraint(toView: viewB, attribute: .Right, relation: .LessThanOrEqual, constant: 10.0)</code>

Note: The <code>toView</code> parameter is still optional since for some Auto Layout relations the other view is necessary but for others it's not e.g. height relation of view A to view B vs. height relation of view A to a fixed constant. Cocoa will throw an NSException letting you know what's wrong and in case that behaviour changes we don't want to wrap that with the helper. 
### Description
- Updated 
  - <code>addLeftConstraint</code>
  - <code>addRightConstraint</code>
  - <code>addTopConstraint</code>
  - <code>addBottomConstraint</code>
  - <code>addHeightConstraint</code>
  - <code>addWidthConstraint</code>
  - <code>addCenterXConstraint</code>
  - <code>addCenterYConstraint</code> 

methods to have default parameter values for <code>toView</code>, <code>attribute:</code>, <code>relation</code>, <code>constant</code>. 
- Updated <code>fillSuperview</code> method to have default parameter value for <code>UIEdgeInsetsZero</code> so is can be called as <code>viewA.fillSuperview()</code>
- Removed overloaded versions of these methods so that there is a single method now. 
- Updated unit tests 
### Status
- [x] Code review
- [x] Unit Tests
- [x] Manual testing
- [ ] Updated README
### Screenshots

screen shot 2015-11-30 at 18 12 35

cc @chris59david @ylibatsya @danieladias @jamaine-ustwo

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,6 +1,53 @@
...
+#
+# Pods/
+
+# Carthage
+#
+# Add this line if you want to avoid checking in source code from Carthage dependencies.
+# Carthage/Checkouts
+
+Carthage/Build
+
```
Comment (alyapozdnyakova) [inline .gitignore]: Why do you need Carthage/Build here?

File: AutoLayoutHelper/UIView+AutoLayoutHelper.swift [hunk 2]
```diff
@@ -45,12 +45,12 @@ extension UIView {
     
     :returns: An array of 4 x NSLayoutConstraint objects (top, left, bottom , right) if the superview exists (otherwise an empty array)
     */
-    func fillSuperView(edges: UIEdgeInsets) -> [NSLayoutConstraint] {
+    func fillSuperView(edges: UIEdgeInsets = UIEdgeInsetsZero) -> [NSLayoutConstraint] {
```
Comment (alyapozdnyakova) [inline AutoLayoutHelper/UIView+AutoLayoutHelper.swift:48]: Do you think it would be good to add default parameters' description to the documentation for this method (and other methods that got default params in this PR)?

**Comment by alyapozdnyakova** [comment]
@madhikarma this looks awesome! Just a couple of small comments/questions :)

File: .gitignore (hunk 1 above)
Comment (madhikarma) [inline .gitignore]: Sure, I got the ignores from here 

https://github.com/github/gitignore

I can remove Pods and Carthage since its unlikely this project will use dependencies hosted from either of those (and even then its unclear if we want dependencies hosted here)

Related #4

File: AutoLayoutHelper/UIView+AutoLayoutHelper.swift (hunk 2 above)
Comment (madhikarma) [inline AutoLayoutHelper/UIView+AutoLayoutHelper.swift:48]: Sure I'll do that thanks :+1:

File: .gitignore (hunk 1 above)
Comment (alyapozdnyakova) [inline .gitignore]: I was just surprised that only the Carthage/Build was not commented :) But I guess you're right and it's best to remove Pods and Carthage at all

**Comment by madhikarma** [comment]
@ylibatsya Updated as per your code review feedback (thank for that). Worth another look when you have time

**Comment by alyapozdnyakova** [comment]
All good @madhikarma :+1:

**Comment by madhikarma** [comment]
:ship:
